# Site
repository: au-gy/au-gy.github.io
favicon: images/favicon.ico

# Content configuration version
version: 1

# Personal info
name: Guanyan Ou 区冠彦
title: Senior Network System Administrator
email: guanyanou@outlook.com
website: www.github.com/au-gy

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  au-gy
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm an undergraduate student at <b>SYSU</b> (Sun Yat-sen University), majoring in Software Engineering.

  Research on adversarial attack towards AI computer vision models is what I'm proceeding currently in the TAI group, Inplus lab and I'm supervised by Professor Weibin Wu.
  I'm also interested in NLP (natural language processing) and block chain.

  <mark>Python</mark>, <mark>Java</mark>, <mark>JavaScript</mark> and <mark>C/C++</mark> are my most skilled languages.


content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sun Yat-sen University
        caption: 2020 - Present
        sub_title: BEng Software Engineering
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          *GPA*: 3.65/5.0

          *Awards*:
          - Second Prize in SYSU-ICPC, 2022
          - First prize in SYSU-ICPC Novice trial, 2022

          *Language*:
          - Chinese(Mandarin and Cantonese), English(TOEFL 98)

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Blog Community
        link: https://gitee.com/gyau/intermediate-training-blog
        link_text: Gitee Address
        description:
            The front end of the project uses the Ant Design UI library, combined with the pluggable enterprise-class react application framework umi, to achieve the interface UI design and project convention-based routing. The project's back end uses SpringBoot to handle HTTP interactions and the MyBatis framework to generate and eventually execute sql statements.

      - layout: left
        title: Citi Cup
        link: https://www.citigroup.com/china/csts/EducationProgram/AboutEducation_CFCcn.html
        link_text: Official Website
        sub_title: Product Manager & Developer
        description: | # this will include new lines to allow paragraphs
            This project combines financial knowledge graph and natural language processing technologies to build a graph by analyzing public reports of companies to obtain relevant information and use the resulting information to rate different companies and institutions on ESG.

      - layout: left
        title: RPCpico
        description: | # this will include new lines to allow paragraphs
            This project is a RPC (Remote Procedure Call) program implemented with Java. The program provide relatively high preformance and compatibility with HTTP and ProtoBuf.


      # - layout: top-middle
      #   title: Super awesome project
      #   link: github.com/sproogen
      #   # link_text: Project Website
      #   additional_links:
      #     - title:  sproogen/modern-resume-theme
      #       icon: fab fa-github
      #       url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        # description: | # this will include new lines to allow paragraphs
        #   I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
